services:
  - type: web
    name: weather-app
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn weather_project.wsgi:application"
    envVars:
      - key: DJANGO_SECRET_KEY
        value: ll+8+=w$#%h%(qo1a!198j235#!iq^fn30ljez5*e1+0@ptc58
      - key: OPENWEATHER_API_KEY
        value: 424deeea82b2325a0e09c724f449979f
      - key: DEBUG
        value: false
